dataset: path/to/data/ # Dataset path (string)
name: vgg-19 # Job name (string)
weight: /path/to/weight.pt # Pretrained weight file path (string)
imgsz: 256 # Resizing size (int)
lr: 0.001 # Learning Rate (exponential or float)
batch: 16 # Batch size (int)
epoch: 100 # Epochs (int)
case: Adam_XEtrp # Opt_Cri (Opt: Adam, Adamax, SGD // Cri: XEtrp(Cross Entropy), BCE)(string) ※ TBD: Dice & Focal 
