dataset: path/to/data/ # Dataset path (string)
name: vgg-19 # Name of Training sequence (string)
model: vgg19 # VGG model type (vgg19 or vgg16) (string)
weight: /path/to/weight.pt # Pretrained weight file path (string)
num_cls: 2 # Number of Classes (int)
early_stop: 10 # Early Stop Count (int)
imgsz: 256 # Resizing size (int)
lr: 0.001 # Learning Rate (exponential or float)
batch: 16 # Batch size (int)
epoch: 100 # Epochs (int)
case: Adam_XEtrp # Opt_Cri (Opt: Adam, Adamax, SGD // Cri: XEtrp(Cross Entropy), BCE)(string) ※ TBD: Dice & Focal 
